In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../Data/bgg_GameItem.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113904 entries, 0 to 113903
Data columns (total 38 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   bgg_id               113904 non-null  int64
 1   name                 113904 non-null  object
 2   year                 104219 non-null  float64
 3   game_type            25830 non-null   object
 4   designer             95653 non-null   object
 5   artist               47872 non-null   object
 6   publisher            113852 non-null  object
 7   min_players          111966 non-null  float64
 8   max_players          108448 non-null  float64
 9   min_players_rec      111966 non-null  float64
 10  max_players_rec      108448 non-null  float64
 11  min_players_best     111966 non-null  float64
 12  max_players_best     108448 non-null  float64
 13  min_age              90641 non-null   float64
 14  min_age_rec          1126 non-null    float64
 15  min_time             91342 non-null   float64
 16  max_time             91342 non-null   float64
 17  category             111690 non-null  object
 18  mechanic             97137 non-null   object
 19  cooperative          6354 non-null    float64
 20  compilation          915 non-null     float64
 21  compilation_of       915 non-null     object
 22  family               79045 non-null   object
 23  implementation       5865 non-null    object
 24  integration          4120 non-null    object
 25  rank                 24479 non-null   float64
 26  num_votes            86182 non-null   float64
 27  avg_rating           86182 non-null   float64
 28  stddev_rating        68497 non-null   float64
 29  bayes_rating         24934 non-null   float64
 30  complexity           48290 non-null   float64
 31  language_dependency  854 non-null     float64
 32  bga_id               0 non-null       float64
 33  dbpedia_id           0 non-null       float64
 34  luding_id            0 non-null       float64
 35  spielen_id           0 non-null       float64
 36  wikidata_id          0 non-null       float64
 37  wikipedia_id         0 non-null       float64
dtypes: float64(26), int64(1), object(11)
memory usage: 33.0+ MB

In [15]:
df2 = df[["name", "year", "mechanic"]].dropna(axis = 0)
df2 = df2[df2["year"] >= 1900]
df2["year"] = df2["year"].astype(int)

df2

,name,year,mechanic
0,Die Macher,1986,"2916,2080,2012,2072,2040,2020"
1,Dragonmaster,1981,2009
2,Samurai,1998,"2080,2040,2026,2846,2004,2002"
3,Tal der Könige,1992,"2001,2080,2012,2004"
4,Acquire,1964,"2040,2910,2900,2940,2005,2002,2874"
...,...,...,...
113899,Champions!,2023,2017
113900,Leitin að stjörnunni,2022,"2073,2038,2019"
113901,The String Railway Collection,2024,"2011,2081,2007"
113902,SpellBook,2023,"2040,2004,2819"
113903,Nightmares of Sushi,2023,"2857,3002,2875,2040,2047"

In [16]:
unique_mechanics = []

for row in df2["mechanic"]:
    for mechanic in row.split(","):
        if mechanic not in unique_mechanics:
            unique_mechanics.append(mechanic)

unique_mechanics

['2916',
 '2080',
 '2012',
 '2072',
 '2040',
 '2020',
 '2009',
 '2026',
 '2846',
 '2004',
 '2002',
 '2001',
 '2910',
 '2900',
 '2940',
 '2005',
 '2874',
 '2043',
 '2048',
 '2060',
 '2011',
 '2081',
 '2041',
 '2078',
 '2981',
 '2915',
 '2008',
 '2923',
 '2928',
 '2922',
 '2661',
 '2902',
 '2876',
 '2909',
 '2897',
 '2035',
 '2015',
 '2689',
 '2957',
 '2676',
 '2836',
 '2953',
 '2822',
 '2017',
 '2831',
 '2850',
 '2055',
 '2685',
 '2028',
 '2947',
 '2070',
 '2079',
 '2974',
 '2046',
 '2013',
 '2023',
 '3002',
 '2003',
 '2884',
 '2883',
 '2987',
 '2889',
 '2047',
 '2823',
 '3001',
 '2959',
 '2016',
 '2914',
 '2861',
 '2686',
 '2855',
 '2828',
 '2019',
 '2018',
 '2849',
 '2826',
 '2924',
 '2865',
 '2057',
 '2944',
 '2838',
 '2926',
 '2863',
 '2853',
 '2014',
 '2834',
 '2007',
 '2918',
 '2920',
 '2919',
 '2864',
 '2961',
 '2999',
 '2010',
 '2965',
 '3000',
 '2891',
 '2860',
 '2039',
 '2888',
 '2950',
 '2956',
 '2875',
 '2980',
 '3006',
 '2927',
 '2819',
 '2827',
 '2975',
 '2854',
 '2837',
 '2913',
 '2912',
 '3100',
 '2021',
 '2962',
 '2082',
 '2949',
 '2960',
 '2988',
 '2939',
 '2948',
 '2857',
 '2955',
 '2911',
 '2871',
 '2967',
 '2904',
 '2984',
 '3004',
 '2833',
 '2858',
 '2963',
 '3005',
 '2930',
 '2866',
 '2841',
 '2829',
 '2978',
 '2954',
 '2840',
 '2906',
 '2856',
 '2985',
 '2882',
 '2847',
 '2933',
 '2851',
 '2027',
 '2887',
 '2073',
 '2038',
 '3101',
 '2892',
 '2814',
 '2958',
 '2820',
 '2952',
 '2893',
 '2991',
 '2990',
 '2870',
 '2946',
 '2901',
 '2664',
 '2821',
 '3007',
 '3096',
 '3099',
 '3003',
 '2989',
 '2964',
 '2843',
 '2663',
 '2885',
 '2931',
 '2844',
 '2835',
 '3102',
 '2886',
 '2839',
 '2830',
 '2813',
 '2935',
 '2903',
 '2932',
 '3104',
 '3097',
 '2824',
 '3098',
 '3103']

In [17]:
for mechanic in unique_mechanics:
    df2[mechanic] = 0

df2.head()

/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0
/var/folders/18/6nr8f3q94w39k_j09mvvhkjm0000gn/T/ipykernel_72643/1870894486.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df2[mechanic] = 0

,name,year,mechanic,2916,2080,2012,2072,2040,2020,2009,...,2830,2813,2935,2903,2932,3104,3097,2824,3098,3103
0,Die Macher,1986,"2916,2080,2012,2072,2040,2020",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Dragonmaster,1981,2009,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Samurai,1998,"2080,2040,2026,2846,2004,2002",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Tal der Könige,1992,"2001,2080,2012,2004",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Acquire,1964,"2040,2910,2900,2940,2005,2002,2874",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
for index, row in df2.iterrows():
    mechanics = row["mechanic"].split(",")
    for mechanic in mechanics:
        df2.at[index, mechanic] = 1

#for row in df2["mechanic"]:
#      row_mechanics = row.split(",") 
#for mechanic in unique_mechanics: 
#   mechanic_columns[mechanic].append(1 if mechanic in row_mechanics else 0)
   
df2

,name,year,mechanic,2916,2080,2012,2072,2040,2020,2009,...,2830,2813,2935,2903,2932,3104,3097,2824,3098,3103
0,Die Macher,1986,"2916,2080,2012,2072,2040,2020",1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,Dragonmaster,1981,2009,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,Samurai,1998,"2080,2040,2026,2846,2004,2002",0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Tal der Könige,1992,"2001,2080,2012,2004",0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Acquire,1964,"2040,2910,2900,2940,2005,2002,2874",0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113899,Champions!,2023,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113900,Leitin að stjörnunni,2022,"2073,2038,2019",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113901,The String Railway Collection,2024,"2011,2081,2007",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113902,SpellBook,2023,"2040,2004,2819",0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
113903,Nightmares of Sushi,2023,"2857,3002,2875,2040,2047",0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
mechanic_names = pd.read_csv("../Data/bgg_Mechanic.csv")

mechanic_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   bgg_id  191 non-null    int64
 1   name    191 non-null    object
dtypes: int64(1), object(1)
memory usage: 3.1+ KB

In [20]:
df2_rename = dict(zip(mechanic_names["bgg_id"].astype(str), mechanic_names["name"]))

df2.rename(columns = df2_rename, inplace=True)

df2

,name,year,mechanic,Alliances,Area Majority / Influence,Auction/Bidding,Dice Rolling,Hand Management,Simultaneous Action Selection,Trick-taking,...,Turn Order: Pass Order,Rondel,Worker Placement with Dice Workers,Automatic Resource Growth,Auction: Dutch Priority,Neighbor Scope,Bids As Wagers,Legacy Game,Auction Compensation,Resource Queue
0,Die Macher,1986,"2916,2080,2012,2072,2040,2020",1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,Dragonmaster,1981,2009,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,Samurai,1998,"2080,2040,2026,2846,2004,2002",0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Tal der Könige,1992,"2001,2080,2012,2004",0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Acquire,1964,"2040,2910,2900,2940,2005,2002,2874",0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113899,Champions!,2023,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113900,Leitin að stjörnunni,2022,"2073,2038,2019",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113901,The String Railway Collection,2024,"2011,2081,2007",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113902,SpellBook,2023,"2040,2004,2819",0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
113903,Nightmares of Sushi,2023,"2857,3002,2875,2040,2047",0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
df2.to_csv("Mechanics_over_Time_labelled.csv")

In [22]:
df2_melt = df2.melt(id_vars = ["name", "year", "mechanic"], value_vars = df2.columns[3:], var_name = "mechanic_name", value_name = "exists")

df2_melt

,name,year,mechanic,mechanic_name,exists
0,Die Macher,1986,"2916,2080,2012,2072,2040,2020",Alliances,1
1,Dragonmaster,1981,2009,Alliances,0
2,Samurai,1998,"2080,2040,2026,2846,2004,2002",Alliances,0
3,Tal der Könige,1992,"2001,2080,2012,2004",Alliances,0
4,Acquire,1964,"2040,2910,2900,2940,2005,2002,2874",Alliances,0
...,...,...,...,...,...
16947998,Champions!,2023,2017,Resource Queue,0
16947999,Leitin að stjörnunni,2022,"2073,2038,2019",Resource Queue,0
16948000,The String Railway Collection,2024,"2011,2081,2007",Resource Queue,0
16948001,SpellBook,2023,"2040,2004,2819",Resource Queue,0
16948002,Nightmares of Sushi,2023,"2857,3002,2875,2040,2047",Resource Queue,0

In [23]:
df2_melt.columns = ["Name", "Year", "Mechanics Set", "Mechanic", "exists"]

df2_melt

,Name,Year,Mechanics Set,Mechanic,exists
0,Die Macher,1986,"2916,2080,2012,2072,2040,2020",Alliances,1
1,Dragonmaster,1981,2009,Alliances,0
2,Samurai,1998,"2080,2040,2026,2846,2004,2002",Alliances,0
3,Tal der Könige,1992,"2001,2080,2012,2004",Alliances,0
4,Acquire,1964,"2040,2910,2900,2940,2005,2002,2874",Alliances,0
...,...,...,...,...,...
16947998,Champions!,2023,2017,Resource Queue,0
16947999,Leitin að stjörnunni,2022,"2073,2038,2019",Resource Queue,0
16948000,The String Railway Collection,2024,"2011,2081,2007",Resource Queue,0
16948001,SpellBook,2023,"2040,2004,2819",Resource Queue,0
16948002,Nightmares of Sushi,2023,"2857,3002,2875,2040,2047",Resource Queue,0

In [24]:
df2_melt_cleaned = df2_melt[df2_melt["exists"] == 1].drop(columns = ["exists"]).sort_values(["Year", "Name"])

df2_melt_cleaned

,Name,Year,Mechanics Set,Mechanic
189867,1001,1900,"2012,2009",Auction/Bidding
544799,1001,1900,"2012,2009",Trick-taking
3159727,A Trip Through Europe,1900,2035,Roll / Spin and Move
351567,Afrika Reisende,1900,"2072,2876,2035,2939",Dice Rolling
2924824,Afrika Reisende,1900,"2072,2876,2035,2939",Race
...,...,...,...,...
4769444,Template of War,2026,"2080,2046,2018,2023,2664,2072,2011,2041,2028,2...",Area Movement
4946910,Template of War,2026,"2080,2046,2018,2023,2664,2072,2011,2041,2028,2...",Cooperative Game
6544104,Template of War,2026,"2080,2046,2018,2023,2664,2072,2011,2041,2028,2...",Campaign / Battle Card Driven
13199079,Template of War,2026,"2080,2046,2018,2023,2664,2072,2011,2041,2028,2...",Storytelling
14618807,Template of War,2026,"2080,2046,2018,2023,2664,2072,2011,2041,2028,2...","Deck, Bag, and Pool Building"

In [25]:
df2_melt_cleaned.to_csv("Mechanics_over_Time_melt.csv")