In [1]:
# https://www.kaggle.com/datasets/mshepherd/board-games?select=bgg_Category.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../Data/luding_GameItem.csv")

df

,bgg_id,name,year,game_type,designer,artist,publisher,min_players,max_players,min_players_rec,...,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
0,6706.0,Xerxes,1973.0,Board,Kurt Heuser,NaN,F.X. Schmid,2.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN
1,NaN,Das Krokodil-Spiel,1987.0,Board,Johann Rüttinger,NaN,noris,2.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN
2,NaN,Conquest,1987.0,Board,Donald Benge,NaN,Hexagames / TST-Enterprises,2.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN
3,NaN,Momo,1987.0,Board,"Stefanie Rohner,Christian Wolf",NaN,Herder Verlag,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN
4,NaN,Drachenfels,1986.0,Board,"Leo Colovini,Alex Randolph",NaN,Schmidt,2.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35044,NaN,Tiwanaku,NaN,Board,Olivier Grégoire,Raphaël Samakh,Sit Down!,1.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,37415,NaN,NaN,NaN
35045,NaN,Moesteiro,NaN,Board,"Rôla,Costa","Pedro Soto,Chema Román",Pythagoras,2.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,37416,NaN,NaN,NaN
35046,NaN,Get it!,NaN,Board,Steffen Benndorf,Christian Opperer,Kendi,3.0,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,37417,NaN,NaN,NaN
35047,NaN,St. Patrick,NaN,Board,"Haig Tahta,Sacha Tahta Alexander",Bastien Jez,"Abacusspiele,Matagot",3.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,37418,NaN,NaN,NaN
35048,NaN,Café del Gatto,NaN,Board,"Lena Burkhardt,Julia Wagner",Robin Struss,Schmidt,2.0,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,37419,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35049 entries, 0 to 35048
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   bgg_id               3904 non-null   float64
 1   name                 35049 non-null  object
 2   year                 14747 non-null  float64
 3   game_type            35048 non-null  object
 4   designer             24948 non-null  object
 5   artist               4201 non-null   object
 6   publisher            33965 non-null  object
 7   min_players          27518 non-null  float64
 8   max_players          26400 non-null  float64
 9   min_players_rec      0 non-null      float64
 10  max_players_rec      0 non-null      float64
 11  min_players_best     0 non-null      float64
 12  max_players_best     0 non-null      float64
 13  min_age              22292 non-null  float64
 14  min_age_rec          0 non-null      float64
 15  min_time             0 non-null      float64
 16  max_time             0 non-null      float64
 17  category             0 non-null      float64
 18  mechanic             0 non-null      float64
 19  cooperative          0 non-null      float64
 20  compilation          0 non-null      float64
 21  compilation_of       0 non-null      float64
 22  family               0 non-null      float64
 23  implementation       0 non-null      float64
 24  integration          0 non-null      float64
 25  rank                 0 non-null      float64
 26  num_votes            0 non-null      float64
 27  avg_rating           0 non-null      float64
 28  stddev_rating        0 non-null      float64
 29  bayes_rating         0 non-null      float64
 30  complexity           0 non-null      float64
 31  language_dependency  0 non-null      float64
 32  bga_id               0 non-null      float64
 33  dbpedia_id           0 non-null      float64
 34  luding_id            35049 non-null  int64
 35  spielen_id           0 non-null      float64
 36  wikidata_id          0 non-null      float64
 37  wikipedia_id         0 non-null      float64
dtypes: float64(32), int64(1), object(5)
memory usage: 10.2+ MB

In [5]:
df.describe()

,bgg_id,year,min_players,max_players,min_players_rec,max_players_rec,min_players_best,max_players_best,min_age,min_age_rec,...,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
count,3904.000000,14747.000000,27518.000000,26400.000000,0.0,0.0,0.0,0.0,22292.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,35049.000000,0.0,0.0,0.0
mean,7181.825564,1994.824914,2.061669,5.162803,NaN,NaN,NaN,NaN,9.214068,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19083.415504,NaN,NaN,NaN
std,4422.842104,34.474995,1.693577,6.263511,NaN,NaN,NaN,NaN,3.751012,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,10620.150189,NaN,NaN,NaN
min,5.000000,6.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,1.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
25%,3245.750000,1987.000000,2.000000,4.000000,NaN,NaN,NaN,NaN,7.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,10285.000000,NaN,NaN,NaN
50%,7235.500000,1996.000000,2.000000,4.000000,NaN,NaN,NaN,NaN,9.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19088.000000,NaN,NaN,NaN
75%,11034.250000,2006.000000,2.000000,6.000000,NaN,NaN,NaN,NaN,12.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,28168.000000,NaN,NaN,NaN
max,16035.000000,2023.000000,255.000000,255.000000,NaN,NaN,NaN,NaN,240.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,37419.000000,NaN,NaN,NaN