In [1]:
# https://www.kaggle.com/datasets/mshepherd/board-games?select=bgg_Category.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../Data/wikidata_GameItem.csv")

df

,bgg_id,name,year,game_type,designer,artist,publisher,min_players,max_players,min_players_rec,...,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
0,241590.0,Smart 10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,33526.0,NaN,Q100272319,NaN
1,15832.0,Professional eater,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q1004599,Cheat_(game)
2,NaN,夾食,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q10050812,NaN
3,NaN,"Wagic, The Homebrew ?!",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q100722100,NaN
4,227789.0,Heaven & Ale,NaN,NaN,"Michael Kiesling,مايكل كيسلينج",NaN,Eggertspiele,2.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,32015.0,NaN,Q100796922,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5792,245655.0,The King's Dilemma,NaN,NaN,NaN,NaN,NaN,3.0,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,33746.0,NaN,Q99769245,NaN
5793,NaN,Fekete dáma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q998234,NaN
5794,NaN,Laser tag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q998303,Laser_tag
5795,41302.0,First Orchard,NaN,NaN,NaN,NaN,"Habermaaß,Haba,HABA",1.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q99976134,NaN
5796,NaN,Ferbli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q999946,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5797 entries, 0 to 5796
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   bgg_id               2772 non-null   float64
 1   name                 5797 non-null   object
 2   year                 0 non-null      float64
 3   game_type            0 non-null      float64
 4   designer             589 non-null    object
 5   artist               24 non-null     object
 6   publisher            646 non-null    object
 7   min_players          599 non-null    float64
 8   max_players          582 non-null    float64
 9   min_players_rec      0 non-null      float64
 10  max_players_rec      0 non-null      float64
 11  min_players_best     0 non-null      float64
 12  max_players_best     0 non-null      float64
 13  min_age              30 non-null     float64
 14  min_age_rec          0 non-null      float64
 15  min_time             0 non-null      float64
 16  max_time             0 non-null      float64
 17  category             0 non-null      float64
 18  mechanic             0 non-null      float64
 19  cooperative          0 non-null      float64
 20  compilation          0 non-null      float64
 21  compilation_of       0 non-null      float64
 22  family               0 non-null      float64
 23  implementation       0 non-null      float64
 24  integration          0 non-null      float64
 25  rank                 0 non-null      float64
 26  num_votes            0 non-null      float64
 27  avg_rating           0 non-null      float64
 28  stddev_rating        0 non-null      float64
 29  bayes_rating         0 non-null      float64
 30  complexity           0 non-null      float64
 31  language_dependency  0 non-null      float64
 32  bga_id               9 non-null      object
 33  dbpedia_id           0 non-null      float64
 34  luding_id            1011 non-null   float64
 35  spielen_id           0 non-null      float64
 36  wikidata_id          5797 non-null   object
 37  wikipedia_id         3141 non-null   object
dtypes: float64(31), object(7)
memory usage: 1.7+ MB

In [5]:
df.describe()

,bgg_id,year,game_type,min_players,max_players,min_players_rec,max_players_rec,min_players_best,max_players_best,min_age,...,rank,num_votes,avg_rating,stddev_rating,bayes_rating,complexity,language_dependency,dbpedia_id,luding_id,spielen_id
count,2772.000000,0.0,0.0,599.000000,582.000000,0.0,0.0,0.0,0.0,30.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1011.000000,0.0
mean,65033.284993,NaN,NaN,2.056761,5.158076,NaN,NaN,NaN,NaN,8.200000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18704.096934,NaN
std,91666.065552,NaN,NaN,0.701253,6.297755,NaN,NaN,NaN,NaN,3.294719,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11568.759109,NaN
min,1.000000,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000000,NaN
25%,3093.750000,NaN,NaN,2.000000,4.000000,NaN,NaN,NaN,NaN,7.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9290.000000,NaN
50%,17009.500000,NaN,NaN,2.000000,4.000000,NaN,NaN,NaN,NaN,8.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20203.000000,NaN
75%,107833.000000,NaN,NaN,2.000000,6.000000,NaN,NaN,NaN,NaN,10.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29372.500000,NaN
max,381999.000000,NaN,NaN,7.000000,100.000000,NaN,NaN,NaN,NaN,18.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37315.000000,NaN