In [1]:
# https://www.kaggle.com/datasets/mshepherd/board-games?select=bgg_Category.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../Data/bga_GameItem.csv")

df

,bgg_id,name,year,game_type,designer,artist,publisher,min_players,max_players,min_players_rec,...,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
0,NaN,Sword and Sail,2004.0,NaN,"id,num_games,score,game,url,images",NaN,"name,id,url,num_games,score,game,images",2.0,5.0,NaN,...,NaN,NaN,NaN,NaN,002IJykbze,NaN,NaN,NaN,NaN,NaN
1,NaN,Lords of Vegas: Underworld – Vegas Shutdown Pr...,2020.0,NaN,"id,num_games,score,game,url,images",NaN,"name,id,url,num_games,score,game,images",2.0,4.0,NaN,...,NaN,NaN,NaN,NaN,006hZ0EM7o,NaN,NaN,NaN,NaN,NaN
2,NaN,Charon,1996.0,NaN,"id,num_games,score,game,url,images",Andreas Lenz,"name,id,url,num_games,score,game,images",2.0,4.0,NaN,...,NaN,NaN,NaN,NaN,007646Mm8B,NaN,NaN,NaN,NaN,NaN
3,NaN,Fotbolls-MIG,2010.0,NaN,NaN,NaN,"name,id,url,num_games,score,game,images",2.0,2.0,NaN,...,NaN,NaN,NaN,NaN,007nZoHMje,NaN,NaN,NaN,NaN,NaN
4,NaN,Profiteers,NaN,NaN,"id,num_games,score,game,url,images",NaN,"name,id,url,num_games,score,game,images",3.0,5.0,NaN,...,NaN,NaN,NaN,NaN,008xXY6De5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124021,NaN,A Leader of Men,2008.0,NaN,"id,num_games,score,game,url,images",NaN,"name,id,url,num_games,score,game,images",1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,zzmnQwYHdR,NaN,NaN,NaN,NaN,NaN
124022,NaN,Force of Will,2014.0,NaN,NaN,NaN,"name,id,url,num_games,score,game,images",2.0,2.0,NaN,...,NaN,NaN,NaN,NaN,zzmsZaTDjT,NaN,NaN,NaN,NaN,NaN
124023,NaN,Rattlesnake City,2007.0,NaN,"id,num_games,score,game,url,images",Gérard Mathieu,"name,id,url,num_games,score,game,images",2.0,6.0,NaN,...,NaN,NaN,NaN,NaN,zznezb8q8S,NaN,NaN,NaN,NaN,NaN
124024,NaN,Wrap Cut Bang,1979.0,NaN,"id,num_games,score,game,url,images",NaN,"name,id,url,num_games,score,game,images",2.0,2.0,NaN,...,NaN,NaN,NaN,NaN,zzsKDadosi,NaN,NaN,NaN,NaN,NaN
124025,NaN,Asteroid Racers,2008.0,NaN,"id,num_games,score,game,url,images",Robert Hemminger,"name,id,url,num_games,score,game,images",2.0,6.0,NaN,...,NaN,NaN,NaN,NaN,zzyeuptZgA,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124026 entries, 0 to 124025
Data columns (total 38 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   bgg_id               0 non-null       float64
 1   name                 124026 non-null  object
 2   year                 100194 non-null  float64
 3   game_type            0 non-null       float64
 4   designer             70088 non-null   object
 5   artist               41919 non-null   object
 6   publisher            96154 non-null   object
 7   min_players          105590 non-null  float64
 8   max_players          105478 non-null  float64
 9   min_players_rec      0 non-null       float64
 10  max_players_rec      0 non-null       float64
 11  min_players_best     0 non-null       float64
 12  max_players_best     0 non-null       float64
 13  min_age              84354 non-null   float64
 14  min_age_rec          0 non-null       float64
 15  min_time             86505 non-null   float64
 16  max_time             86393 non-null   float64
 17  category             13829 non-null   object
 18  mechanic             19253 non-null   object
 19  cooperative          0 non-null       float64
 20  compilation          0 non-null       float64
 21  compilation_of       0 non-null       float64
 22  family               0 non-null       float64
 23  implementation       0 non-null       float64
 24  integration          0 non-null       float64
 25  rank                 0 non-null       float64
 26  num_votes            123033 non-null  float64
 27  avg_rating           21247 non-null   float64
 28  stddev_rating        0 non-null       float64
 29  bayes_rating         0 non-null       float64
 30  complexity           0 non-null       float64
 31  language_dependency  0 non-null       float64
 32  bga_id               124026 non-null  object
 33  dbpedia_id           0 non-null       float64
 34  luding_id            0 non-null       float64
 35  spielen_id           0 non-null       float64
 36  wikidata_id          0 non-null       float64
 37  wikipedia_id         0 non-null       float64
dtypes: float64(31), object(7)
memory usage: 36.0+ MB

In [5]:
df.describe()

,bgg_id,year,game_type,min_players,max_players,min_players_rec,max_players_rec,min_players_best,max_players_best,min_age,...,avg_rating,stddev_rating,bayes_rating,complexity,language_dependency,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
count,0.0,100194.000000,0.0,105590.000000,105478.000000,0.0,0.0,0.0,0.0,84354.000000,...,21247.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,2001.450596,NaN,2.014206,6.329329,NaN,NaN,NaN,NaN,9.797330,...,3.236286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,35.936881,NaN,0.819033,58.184782,NaN,NaN,NaN,NaN,7.692212,...,0.814322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,100.000000,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,1.000000,...,0.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1997.000000,NaN,2.000000,2.000000,NaN,NaN,NaN,NaN,8.000000,...,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,2009.000000,NaN,2.000000,4.000000,NaN,NaN,NaN,NaN,10.000000,...,3.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,2016.000000,NaN,2.000000,6.000000,NaN,NaN,NaN,NaN,12.000000,...,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,2024.000000,NaN,50.000000,11299.000000,NaN,NaN,NaN,NaN,2020.000000,...,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN