In [2]:
# https://www.kaggle.com/datasets/mshepherd/board-games?select=bgg_Category.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("../Data/bgg_GameItem.csv")

df

,bgg_id,name,year,game_type,designer,artist,publisher,min_players,max_players,min_players_rec,...,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
0,1,Die Macher,1986.0,5497,1,"12517,4959","133,2,24883,2726,15108,39249,11652,5382,8147",3.0,5.0,4.0,...,1.57510,7.06367,4.3144,1.166667,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Dragonmaster,1981.0,5497,8384,12424,"64,20",3.0,4.0,3.0,...,1.46752,5.76599,1.9636,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Samurai,1998.0,5497,2,11883,"17,133,267,29,7340,7335,41,2973,4617,1391,8291...",2.0,4.0,2.0,...,1.19279,7.22869,2.4784,1.006579,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Tal der Könige,1992.0,5497,8008,2277,37,2.0,4.0,2.0,...,1.23667,5.66660,2.6667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Acquire,1964.0,5497,4,"12658,18317","92,5,4871,3082,858,2962,28072,5392,4668,38,462...",2.0,6.0,3.0,...,1.33603,7.12541,2.4985,1.095890,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113899,391565,Champions!,2023.0,NaN,"62310,62311,6736",NaN,"4384,1391",3.0,8.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113900,391715,Leitin að stjörnunni,2022.0,NaN,"154290,123339,154289",NaN,54258,2.0,20.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113901,391720,The String Railway Collection,2024.0,NaN,39436,113637,44392,2.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113902,391834,SpellBook,2023.0,NaN,8347,45292,25842,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113903,392146,Nightmares of Sushi,2023.0,NaN,81537,81537,52244,2.0,6.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113904 entries, 0 to 113903
Data columns (total 38 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   bgg_id               113904 non-null  int64
 1   name                 113904 non-null  object
 2   year                 104219 non-null  float64
 3   game_type            25830 non-null   object
 4   designer             95653 non-null   object
 5   artist               47872 non-null   object
 6   publisher            113852 non-null  object
 7   min_players          111966 non-null  float64
 8   max_players          108448 non-null  float64
 9   min_players_rec      111966 non-null  float64
 10  max_players_rec      108448 non-null  float64
 11  min_players_best     111966 non-null  float64
 12  max_players_best     108448 non-null  float64
 13  min_age              90641 non-null   float64
 14  min_age_rec          1126 non-null    float64
 15  min_time             91342 non-null   float64
 16  max_time             91342 non-null   float64
 17  category             111690 non-null  object
 18  mechanic             97137 non-null   object
 19  cooperative          6354 non-null    float64
 20  compilation          915 non-null     float64
 21  compilation_of       915 non-null     object
 22  family               79045 non-null   object
 23  implementation       5865 non-null    object
 24  integration          4120 non-null    object
 25  rank                 24479 non-null   float64
 26  num_votes            86182 non-null   float64
 27  avg_rating           86182 non-null   float64
 28  stddev_rating        68497 non-null   float64
 29  bayes_rating         24934 non-null   float64
 30  complexity           48290 non-null   float64
 31  language_dependency  854 non-null     float64
 32  bga_id               0 non-null       float64
 33  dbpedia_id           0 non-null       float64
 34  luding_id            0 non-null       float64
 35  spielen_id           0 non-null       float64
 36  wikidata_id          0 non-null       float64
 37  wikipedia_id         0 non-null       float64
dtypes: float64(26), int64(1), object(11)
memory usage: 33.0+ MB

In [6]:
df.describe()

,bgg_id,year,min_players,max_players,min_players_rec,max_players_rec,min_players_best,max_players_best,min_age,min_age_rec,...,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
count,113904.000000,104219.000000,111966.000000,108448.000000,111966.000000,108448.000000,111966.000000,108448.000000,90641.000000,1126.000000,...,68497.000000,24934.000000,48290.000000,854.000000,0.0,0.0,0.0,0.0,0.0,0.0
mean,156348.970185,2001.765551,2.020703,6.908306,2.025892,6.887328,2.061403,6.861168,9.517437,9.863855,...,1.511145,5.677975,1.902059,2.113773,NaN,NaN,NaN,NaN,NaN,NaN
std,124025.337022,66.493704,0.817943,49.819444,0.823590,49.807438,0.862756,49.809422,7.471185,2.824199,...,0.625139,0.357619,0.830024,1.191279,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,-3500.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.045455,...,0.000500,3.624890,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,32767.750000,1998.000000,2.000000,4.000000,2.000000,4.000000,2.000000,4.000000,8.000000,7.987899,...,1.176210,5.509562,1.000000,1.013607,NaN,NaN,NaN,NaN,NaN,NaN
50%,140110.500000,2011.000000,2.000000,4.000000,2.000000,4.000000,2.000000,4.000000,10.000000,10.000000,...,1.465140,5.541855,2.000000,1.778424,NaN,NaN,NaN,NaN,NaN,NaN
75%,268252.500000,2018.000000,2.000000,6.000000,2.000000,6.000000,2.000000,6.000000,12.000000,11.973319,...,1.776240,5.662987,2.414025,3.063077,NaN,NaN,NaN,NaN,NaN,NaN
max,392146.000000,2026.000000,50.000000,11299.000000,50.000000,11299.000000,50.000000,11299.000000,2017.000000,20.541667,...,4.500000,8.423300,5.000000,4.983333,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df["category"]

0              1021,1026,1001
1                   1002,1010
2                   1009,1035
3                        1050
4                   1021,1086
                 ...
113899                   1030
113900    1041,1064,1030,1027
113901              1086,1034
113902                   1010
113903         1002,1039,1079
Name: category, Length: 113904, dtype: object

In [8]:
df["mechanic"]

0              2916,2080,2012,2072,2040,2020
1                                       2009
2              2080,2040,2026,2846,2004,2002
3                        2001,2080,2012,2004
4         2040,2910,2900,2940,2005,2002,2874
                         ...
113899                                  2017
113900                        2073,2038,2019
113901                        2011,2081,2007
113902                        2040,2004,2819
113903              2857,3002,2875,2040,2047
Name: mechanic, Length: 113904, dtype: object